services:
  notebook:
    build: .
    volumes:
      - ./output:/app/output
    environment:
      - TF_CPP_MIN_LOG_LEVEL=2

  shell:
    build: .
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    command: bash
